In [1]:
from datetime import datetime
import tensorflow as tf
import importlib
import numpy as np



In [2]:
# import config 
import configs.config
importlib.reload(configs.config)
from configs.config import CFG
from utils import config
config = config.Config.from_json(CFG)

## Create Dataset

In [3]:
# create Train Series and Dataset 
import dataloader.dataloader
importlib.reload(dataloader.dataloader)
from dataloader.dataloader import Train_Series,Dataset
try: 
    del series,ds
except:
    pass
from dataloader.dataloader import Test_Series
try: 
    del test_series
except:
    pass

series = Train_Series(config.data,config.paths)
series.createSeries()
test_series = Test_Series(config.data,config.paths)
test_series.createSeries()
ds = Dataset(series,test_series)
ds.split_dataset()

X_train = ds.X_train
y_train = ds.y_train
X_test = ds.X_test
y_test = ds.y_test

print(X_train.shape)
print(X_test.shape)

(78615, 160, 2)
(3, 160, 2)


In [62]:
ms = series.series["03d92c9f6f8a"].get_correct_slices() 
ms.shape

(191, 160, 3)

In [66]:
series.series["03d92c9f6f8a"].slices.shape

(240, 160, 3)

In [22]:
for serie_id, serie in series.series.items(): 
    for i in range(y_train.shape[0]):
        nextSlice = False
        for val in serie.encode_list.values():
            if np.all(y_train[i,:,2]== val):
                nextSlice = True
                break
        if nextSlice == True :
            continue
        else:
            print(y_train[i,:,2])
        break
    


[0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0.

In [23]:
y_train.shape

(6668, 160, 1)

In [29]:
length = 0
for i in range(y_train.shape[0]):
    nextSlice = False
    for val in serie.encode_list.values():
        if np.all(y_train[i,:,0]== val):
            nextSlice = True
            break
    if nextSlice == True :
        continue
    else:
        #print(i)
        length +=1
        print(y_train[i,:,0])
    
print(length)


[2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1.

## Save Datset to Files 

In [5]:
import pickle
# Include the epoch in the file name (uses `str.format`)
ds_path = "./model/saved_ds/ds.obj"

with  open(ds_path,'wb') as file:
    exampleObj = pickle.dump(ds,file)


## Call model and compile

In [4]:
from model.model1D import Unet,Unet_Model
import model.model1D
importlib.reload(model.model1D)
try: 
    del unet
except:
    pass

unet = Unet(n_classes=3,n_filters=8)
unet.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
unet.model((160,2)).summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 160, 2)]     0           []                               
                                                                                                  
 downsampling_block (Downsampli  ((None, 80, 8),     256         ['input_1[0][0]']                
 ngBlock)                        (None, 160, 8))                                                  
                                                                                                  
 downsampling_block_1 (Downsamp  ((None, 40, 16),    1184        ['downsampling_block[0][0]']     
 lingBlock)                      (None, 80, 16))                                                  
                                                                                              

## Train Model and save weights and model to files

In [5]:
from datetime import datetime
#train model
history = unet.fit(X_train,y_train,epochs = 10,batch_size=64)




Epoch 1/10
1229/1229 [==============================] - 42s 30ms/step - loss: 0.2648 - accuracy: 0.9103
Epoch 2/10
1229/1229 [==============================] - 38s 31ms/step - loss: 0.2146 - accuracy: 0.9254
Epoch 3/10
1229/1229 [==============================] - 37s 30ms/step - loss: 0.2099 - accuracy: 0.9267
Epoch 4/10
1229/1229 [==============================] - 38s 31ms/step - loss: 0.2056 - accuracy: 0.9287
Epoch 5/10
1229/1229 [==============================] - 37s 30ms/step - loss: 0.2031 - accuracy: 0.9292
Epoch 6/10
1229/1229 [==============================] - 39s 32ms/step - loss: 0.2011 - accuracy: 0.9300
Epoch 7/10
1229/1229 [==============================] - 37s 30ms/step - loss: 0.1986 - accuracy: 0.9308
Epoch 8/10
1229/1229 [==============================] - 38s 31ms/step - loss: 0.1979 - accuracy: 0.9311
Epoch 9/10
1229/1229 [==============================] - 38s 31ms/step - loss: 0.1965 - accuracy: 0.9315
Epoch 10/10
1229/1229 [==============================] - 39s 32m

In [ ]:
# Include the epoch in the file name (uses `str.format`)
checkpoint_path = "model/weights/cp-{epoch:04d}.ckpt"
# save weights 
unet.save_weights(checkpoint_path.format(epoch=100))
#save model
models_path = "model/saved_models/unet_{version}_{now}"
unet.save(models_path.format(version = "v1", now = str(datetime.now().date())))

In [32]:
# Include the epoch in the file name (uses `str.format`)
checkpoint_path = "model/weights/cp-{epoch:04d}.ckpt"

# Loads the weights
unet.load_weights(checkpoint_path.format(epoch =100))

# Re-evaluate the model
# loss, acc = unet.evaluate(test_images, test_labels, verbose=2)
# print("Restored model, accuracy: {:5.2f}%".format(100 * acc))

In [50]:
# create Train Series and Dataset 
import dataloader.dataloader
importlib.reload(dataloader.dataloader)
from dataloader.dataloader import Test_Series
try: 
    del test_series
except:
    pass

test_series = Test_Series(config.data,config.paths)
test_series.createSeries()

In [54]:
import pandas as pd

In [69]:
def create_events(y_pred :np.array,serie):
    """create df_events 
    input:
    y_pred - score  (predicited vaues )"""
    def detectChange(last_val,current_val):
        if last_val == -1 or current_val == -1:
            return False

        return last_val !=current_val

    # create empty dataframe
    df_events = pd.DataFrame(columns=["series_id","step","event","score"])
    # unpad y_pred
    if serie.slice_pads is None:
        y_pred_unpadded = y_pred
    else:
        y_pred_unpadded = serie._unpad(y_pred,serie.slice_pads)
    # create step seg list
    #         - events - segmentation mask
    #         -  score   - predicited vaues for chosen event
    events = np.argmax(y_pred_unpadded,axis = -1,keepdims=True)
    score = np.max(y_pred_unpadded,axis=-1,keepdims=True)      
    for slice_num in range(events.shape[0]):
        for i in range(events.shape[-2]):
            event_val = events[slice_num,i][0]
            event_score = score[slice_num,i][0]
            if i == 0:
                # do not detect anything during first step
                continue
            elif not detectChange(events[slice_num,i-1],event_val):
                continue

            df_events.loc[len(df_events.index)] = [serie.serie_id,i,event_val,event_score]
    
    # decode events 
    print(df_events)
    df_events = serie.decode_events(df_events)
    # save as serie events 
    serie_events = df_events

    return serie_events 

In [6]:
def predict(model,test_serie):
    x = test_serie.slices
    y_pred = model.predict(x)
    serie_events = create_events(y_pred,test_serie)   
    return serie_events

test_series_pred = {}
for serie_id, test_serie in test_series.series.items():
    serie_events = predict(unet,test_serie)
    print(serie_events)b


1/1 [==============================] - 1s 518ms/step


NameError: name 'create_events' is not defined

In [7]:
def predict(model,test_serie):
    x = test_serie.slices

    y_pred = model.predict(x)
    print(y_pred)
    serie_events = test_serie.create_events(y_pred)   
    return serie_events

test_series_pred = {}
y_pred = None
pred_start = False
for serie_id, test_serie in test_series.series.items():
    serie_events = predict(unet,test_serie)
    print(serie_events)
    if pred_start == False:
        y_pred = serie_events
        pred_start = True
    else:
        y_pred = pd.concat([y_pred, serie_events])

print(y_pred)

1/1 [==============================] - 0s 19ms/step
[[[  0.        67.85311   48.804703]
  [  0.        67.98848   48.31006 ]
  [  0.        89.64294   70.36723 ]
  [  0.        84.84949   64.623215]
  [  0.        93.531906  72.95163 ]
  [  0.        75.28506   55.862873]
  [  0.        71.47164   51.435497]
  [  0.        66.198685  46.42348 ]
  [  0.        73.43133   52.621174]
  [  0.        81.31839   60.658287]
  [  0.        94.617195  72.263084]
  [  0.        85.18207   64.67157 ]
  [  0.        96.23074   74.9361  ]
  [  0.        79.416504  58.123974]
  [  0.        71.337234  50.28317 ]
  [  0.        69.935135  48.777203]
  [  0.        76.46845   54.367664]
  [  0.        80.1967    58.797863]
  [  0.        94.88733   73.39168 ]
  [  0.        88.71591   67.552216]
  [  0.       105.90111   84.11683 ]
  [  0.        92.09831   68.645226]
  [  0.        85.443344  62.473095]
  [  0.        83.59721   59.732327]
  [  0.        88.38381   64.118034]
  [  0.        99.77575

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [60]:
from matplotlib import pyplot as plt
plt.plot(history.history["accuracy"])

NameError: name 'history' is not defined

In [18]:
def accuracy(real,pred):
    comp = real == pred
    return np.sum(comp)/(comp.shape[0]*comp.shape[1])


y_train_pred = unet.predict(X_train)
print("train accuracy : " + str(accuracy(y_train,y_train_pred)))


y_test_pred = unet.predict(X_test)
print("test accuracy : " +  str(accuracy(y_test,y_test_pred)))

In [167]:
from IPython.display import FileLink
import pandas as pd

# import os
# os.chdir(r'kaggle/working')'
filename = 'train_' +'.csv'
pd.DataFrame(test_mask).to_csv(filename)

FileLink(filename)



ValueError: Must pass 2-d input. shape=(51, 8640, 3)